### ISSUE TITLE
New release of osclib compatible with eigen>v3_3_9a (or more specifically, `v3_4_0`)

### ISSUE THREAD

**Issue by jedori0228** [CAFAnaFramework/OscLib#12]
Recent `larsoft` (I'm referring to `09_64_00`) depends on `eigen v3_4_0`, but the most recent version of `osclib` available in cvmfs, `v00.20`, still depends on `v3_3_9a`; I see `v00.21` here in github though. This makes it hard to build `larSoft` and `sbnana` simultaneously, as `sbnana` depends on `osclib`. Is there a plan to have new release of `osclib` with `eigen v3_4_0`?

**Comment by gavinsdavies** [comment]
Thanks for posting this issue, @jedori0228.  There is also a request for this from NOvA, so I'm glad you've made the issue to make it more official. It's next on my list to deploy.

**Comment by jedori0228** [comment]
Hi @gavinsdavies, SBN is about to publish new release of `sbnana`, and I wonder if there is a plan of having new `osclib` release in few days.
